
auth0:
  audience: http://quickstart/api
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091/auth/realms/upay

      client:
        registration:
          keycloak:
            client-id: "service-a"
            client-secret: "95056fee-a01d-4967-9f60-29fe4d89dc86"
            authorization-grant-type: "password"

        provider:
          keycloak:
            token-uri: "http://localhost:9091/auth/realms/upay/protocol/openid-connect/token"

keycloak:
  username: "tech-user-service-a"
  password: "1234"

server:
  port: 8181

logging:
  level:
    root: debug